# Generated by Django 4.2.28 on 2026-02-22 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("fresh", "Fresh"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Job",
                "verbose_name_plural": "Saved Jobs",
                "db_table": "saved_jobs",
                "ordering": ["-saved_at"],
                "indexes": [
                    models.Index(fields=["user"], name="saved_jobs_user_id_76c161_idx"),
                    models.Index(fields=["job"], name="saved_jobs_job_id_52a249_idx"),
                    models.Index(
                        fields=["status"], name="saved_jobs_status_ed02c9_idx"
                    ),
                    models.Index(
                        fields=["-saved_at"], name="saved_jobs_saved_a_8d8f77_idx"
                    ),
                ],
                "unique_together": {("user", "job")},
            },
        ),
    ]
