# Generated by Django 4.2.28 on 2026-02-22 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0003_jobcategory_location_scrapelog_job_employment_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobs_count", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_recaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_recaps",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("remote_only", models.BooleanField(default=False)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("never", "Never"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("preferred_send_time", models.TimeField(default="09:00:00")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_by_users",
                        to="jobs.jobcategory",
                    ),
                ),
                (
                    "preferred_companies",
                    models.ManyToManyField(
                        blank=True, related_name="preferred_by_users", to="jobs.company"
                    ),
                ),
                (
                    "preferred_locations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_by_users",
                        to="jobs.location",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_keywords",
                "unique_together": {("user", "keyword")},
            },
        ),
        migrations.CreateModel(
            name="RecapJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_clicked", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
                (
                    "recap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recap_jobs",
                        to="preferences.dailyrecap",
                    ),
                ),
            ],
            options={
                "db_table": "recap_jobs",
                "unique_together": {("recap", "job")},
            },
        ),
    ]
